site_name: "Project: Docs-as-Code"
site_url: https://dac.pbjwrites.info
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    view: material/eye
  font:
    text: Roboto
  favicon: assets/favicon.ico
  logo: assets/logo.png
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.suggest
    - search.suggest
    - search.highlight
    - content.action.view
    - announce.dismiss
  custom_dir: overrides

plugins:
  - privacy
  - search
  - social
  - macros:
      include_yaml:
        - ./product_names.yaml
        - ./var_lib.yaml
        - ./audience_cond.yaml
        - ./env_cond.yaml
      include_dir: include

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pbj-writes
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pbjwrites/
  header1: Reuse
  productName: pbjStand

extra_css:
  - extra.css

nav:

    - index.md
    - Reuse: reuse.md
    - Advanced Web Features: web_stuff.md
    - Doc Linting: doc_linting.md
    - Localization and Internationalization: loc_int.md

copyright: ©PBJ

repo_url: https://github.com/pbj-writes/project_mkdocs_material
repo_name: pbj-writes/project_mkdocs_material
edit_uri: edit/main/docs/

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences