name: Vale Lint

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.vale.ini'
      - '.vale/**'
  push:
    branches:
      - main
    paths:
      - '**/*.md'
      - '.vale.ini'
      - '.vale/**'

# Limit permissions to only what's needed
permissions:
  contents: read
  pull-requests: write

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to fetch all history for comparing changes

      - name: Install Vale
        run: |
          wget https://github.com/errata-ai/vale/releases/download/v3.11.2/vale_3.11.2_Linux_64-bit.tar.gz
          tar -xf vale_3.11.2_Linux_64-bit.tar.gz
          sudo mv vale /usr/local/bin/

      - name: Sync Vale styles
        run: vale sync

      - name: Run Vale
        run: |
          git fetch origin ${{ github.base_ref }}
          CHANGED_FILES=$(git diff --name-only --diff-filter=d origin/${{ github.base_ref }}...HEAD | grep '\.md$' || true)
          if [ -n "$CHANGED_FILES" ]; then
            echo "Checking files:"
            echo "$CHANGED_FILES"
            vale $CHANGED_FILES
          else
            echo "No Markdown files changed"
          fi